services:
  base: &base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        EXECJS_RUNTIME: 'Node'
        RAILS_ENV: 'production'
    tty: true
    stdin_open: true
    env_file: .docker.env


  rails:
    <<: *base
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - EXECJS_RUNTIME=Node
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always

  sidekiq:
    <<: *base
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - EXECJS_RUNTIME=Node
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always
